name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
=======
      - uses: actions/checkout@v3
      - uses: asdf-vm/actions/install@v2
>>>>>>> fa19415 (Generate asdf-quarto plugin from template.)
      - run: scripts/lint.bash

  actionlint:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v4
=======
      - uses: actions/checkout@v3
>>>>>>> fa19415 (Generate asdf-quarto plugin from template.)
      - name: Check workflow files
        uses: docker://rhysd/actionlint:1.6.23
        with:
          args: -color
