name: Lint

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic-pr:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - uses: amannn/action-semantic-pull-request@v5.4.0
=======
      - uses: amannn/action-semantic-pull-request@v5.2.0
>>>>>>> fa19415 (Generate asdf-quarto plugin from template.)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
